-- Fix SB03 (plan_id ambiguous en preview_price_batch): la definición corregida y al día
-- está en docs/fix-price-batch-carry-forward.sql junto con apply_price_batch (carry-forward).
--
-- Ejecutá en Supabase SQL Editor el archivo:
--   docs/fix-price-batch-carry-forward.sql
--
-- Ese script reemplaza preview_price_batch y apply_price_batch por las versiones actuales.
