-- Fix SB03/SB06 (plan_id ambiguous / record b has no field plan_id)
--
-- Ejecutá en Supabase SQL Editor:
--   docs/fix-preview-price-batch-b-record-plan-id.sql
--
-- Ese script reemplaza preview_price_batch y agrega preview_price_batch_by_provider.
